[package]
name = "tq"
version = "0.1.1"
authors = ["Penn Bauman <pennbauman@protonmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
pico-args = "0.4"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
